title: Marginally Better blog
author: Rishit Dagli
email:
url: https://rishit-dagli.github.io
twitter:
  username: rishit_dagli
  card: summary
description: I write about Machine Learning.
# social links
twitter_username: rishit_dagli # DO NOT include the @ character, or else the build will fail!
github_username:  Rishit-dagli # DO NOT include the @ character, or else the build will fail!
google_analytics: G-GZHCC07NT1

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
permalink: /:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

kramdown:
  math_engine: mathjax

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-redirect-from
