title: Rishit Dagli's Blog
author: Rishit Dagli
email: rishit.dagli@gmail.com
tagline: Machine Learning, Open Source and Computer Science
url: https://rishit-dagli.github.io
twitter:
  username: rishit_dagli
  card: summary
description: >
  This page is a backup of all the blogs I have written. I write about Machine Learning, Open Source and Computer Science in general.
# social links
twitter_username: rishit_dagli # DO NOT include the @ character, or else the build will fail!
github_username:  Rishit-dagli # DO NOT include the @ character, or else the build will fail!
google_analytics: G-GZHCC07NT1

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

kramdown:
  math_engine: katex

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-redirect-from