---

name: Spell Check
on:
  pull_request:
  push:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check articles for typos
      uses: crate-ci/typos@master
      with: 
        files: ./_posts/*.md